config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models/colsmolvlm
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColIdefics3Processor
    pretrained_model_name_or_path:  "HuggingFaceTB/SmolVLM2-256M-Video-Instruct"
    # num_image_tokens: 2048
    # max_length: 50

  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColIdefics3
    pretrained_model_name_or_path: "HuggingFaceTB/SmolVLM2-256M-Video-Instruct"
    torch_dtype:  !ext torch.bfloat16
    # use_cache: false
    attn_implementation: "flash_attention_2"
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  # dataset:
  #   (): colpali_engine.data.dataset.T2IDataset.from_hf
  #   dataset_name: "TIGER-Lab/MMEB-train"
  #   name: "VisDial"
  #   split: "original"
  #   query_column: "qry"
  #   pos_target_column: "pos_image_path"
  #   neg_target_column: "neg_image_path"
  #   corpus:
  #     (): colpali_engine.data.corpus.LocalCorpus
  #     corpus_path: !path "/home/paulteiletche/VLM2Vec/data/MMEB/MMEB-train/images/VisDial/Train"

  # dataset:
  #   (): colpali_engine.data.dataset.I2TDataset.from_hf
  #   dataset_name: "TIGER-Lab/MMEB-train"
  #   name: "DocVQA"
  #   split: "original"
  #   query_column: "qry_image_path"
  #   pos_target_column: "pos_text"
  #   neg_target_column: "neg_text"
  #   corpus:
  #     (): colpali_engine.data.corpus.LocalCorpus
  #     corpus_path: !path "/home/paulteiletche/VLM2Vec/data/MMEB/MMEB-train/images/DocVQA/Train"

  dataset:
    (): colpali_engine.data.dataset.IRDataset.from_hf
    dataset_name: "manu/colpali-queries"
    split: "train"
    query_column: "query"
    pos_target_column: 
      (): colpali_engine.data.dataset.IRColumn
      column_name: "positive_passages"
      corpus_column: "image"
    neg_target_column:
      (): colpali_engine.data.dataset.IRColumn
      column_name: "negative_passages"
      corpus_column: "image"
    corpus:
      (): colpali_engine.data.corpus.SimpleCorpus.from_hf
      corpus_name_or_path: "manu/colpali-corpus"
      split: "train"
      id_column: null
      
  # max_length: 50
  run_eval: false
  loss_func:
    (): colpali_engine.loss.late_interaction_losses.ColbertPairwiseNegativeCELoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: ./checkpoints/test
    overwrite_output_dir: true
    num_train_epochs: 1
    per_device_train_batch_size: 32
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    # gradient_checkpointing: true
    # 6 x 8 gpus = 48 batch size
    # gradient_accumulation_steps: 4
    per_device_eval_batch_size: 32
    eval_strategy: "no"
    dataloader_num_workers: 4
    # bf16: true
    save_steps: 500
    logging_steps: 10
    eval_steps: 100
    warmup_steps: 100
    learning_rate: 5e-4
    save_total_limit: 1
    # resume_from_checkpoint: true
    # optim: "paged_adamw_8bit"
    # wandb logging
    # wandb_project: "debug"
    run_name: "smolembedder"
    report_to: "wandb"


  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '(.*(model.text_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'
    # target_modules: '(.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'

